const conditonsData = [
  {
    code: 1000,
    day: "Nắng",
    night: "Quang đãng",
    icon: 113,
  },
  {
    code: 1003,
    day: "Có mây một phần",
    night: "Có mây một phần",
    icon: 116,
  },
  {
    code: 1006,
    day: "Có mây",
    night: "Có mây",
    icon: 119,
  },
  {
    code: 1009,
    day: "Trời âm u",
    night: "Trời âm u",
    icon: 122,
  },
  {
    code: 1030,
    day: "Sương mù",
    night: "Sương mù",
    icon: 143,
  },
  {
    code: 1063,
    day: "Có thể có mưa rào",
    night: "Có thể có mưa rào",
    icon: 176,
  },
  {
    code: 1066,
    day: "Có thể có tuyết rơi nhẹ",
    night: "Có thể có tuyết rơi nhẹ",
    icon: 179,
  },
  {
    code: 1069,
    day: "Có thể có mưa tuyết nhẹ",
    night: "Có thể có mưa tuyết nhẹ",
    icon: 182,
  },
  {
    code: 1072,
    day: "Có thể có mưa nhỏ đóng băng",
    night: "Có thể có mưa nhỏ đóng băng",
    icon: 185,
  },
  {
    code: 1087,
    day: "Có thể có bão sấm",
    night: "Có thể có bão sấm",
    icon: 200,
  },
  {
    code: 1114,
    day: "Tuyết bay",
    night: "Tuyết bay",
    icon: 227,
  },
  {
    code: 1117,
    day: "Bão tuyết",
    night: "Bão tuyết",
    icon: 230,
  },
  {
    code: 1135,
    day: "Sương mù",
    night: "Sương mù",
    icon: 248,
  },
  {
    code: 1147,
    day: "Sương mù đóng băng",
    night: "Sương mù đóng băng",
    icon: 260,
  },
  {
    code: 1150,
    day: "Mưa nhỏ có thể có",
    night: "Mưa nhỏ có thể có",
    icon: 263,
  },
  {
    code: 1153,
    day: "Mưa nhỏ",
    night: "Mưa nhỏ",
    icon: 266,
  },
  {
    code: 1168,
    day: "Mưa nhỏ đóng băng",
    night: "Mưa nhỏ đóng băng",
    icon: 281,
  },
  {
    code: 1171,
    day: "Mưa nhỏ đóng băng nặng",
    night: "Mưa nhỏ đóng băng nặng",
    icon: 284,
  },
  {
    code: 1180,
    day: "Mưa nhẹ có thể có",
    night: "Mưa nhẹ có thể có",
    icon: 293,
  },
  {
    code: 1183,
    day: "Mưa nhẹ",
    night: "Mưa nhẹ",
    icon: 296,
  },
  {
    code: 1186,
    day: "Mưa vừa thỉnh thoảng",
    night: "Mưa vừa thỉnh thoảng",
    icon: 299,
  },
  {
    code: 1189,
    day: "Mưa vừa",
    night: "Mưa vừa",
    icon: 302,
  },
  {
    code: 1192,
    day: "Mưa nặng thỉnh thoảng",
    night: "Mưa nặng thỉnh thoảng",
    icon: 305,
  },
  {
    code: 1195,
    day: "Mưa nặng",
    night: "Mưa nặng",
    icon: 308,
  },
  {
    code: 1198,
    day: "Mưa đá nhẹ",
    night: "Mưa đá nhẹ",
    icon: 311,
  },
  {
    code: 1201,
    day: "Mưa đá vừa hoặc nặng",
    night: "Mưa đá vừa hoặc nặng",
    icon: 314,
  },
  {
    code: 1204,
    day: "Mưa đá nhẹ",
    night: "Mưa đá nhẹ",
    icon: 317,
  },
  {
    code: 1207,
    day: "Mưa đá vừa hoặc nặng",
    night: "Mưa đá vừa hoặc nặng",
    icon: 320,
  },
  {
    code: 1210,
    day: "Tuyết nhẹ có thể có",
    night: "Tuyết nhẹ có thể có",
    icon: 323,
  },
  {
    code: 1213,
    day: "Tuyết nhẹ",
    night: "Tuyết nhẹ",
    icon: 326,
  },
  {
    code: 1216,
    day: "Tuyết vừa có thể có",
    night: "Tuyết vừa có thể có",
    icon: 329,
  },
  {
    code: 1219,
    day: "Tuyết vừa",
    night: "Tuyết vừa",
    icon: 332,
  },
  {
    code: 1222,
    day: "Tuyết nặng có thể có",
    night: "Tuyết nặng có thể có",
    icon: 335,
  },
  {
    code: 1225,
    day: "Tuyết nặng",
    night: "Tuyết nặng",
    icon: 338,
  },
  {
    code: 1237,
    day: "Hạt băng",
    night: "Hạt băng",
    icon: 350,
  },
  {
    code: 1240,
    day: "Mưa nhẹ",
    night: "Mưa nhẹ",
    icon: 353,
  },
  {
    code: 1243,
    day: "Mưa vừa hoặc nặng",
    night: "Mưa vừa hoặc nặng",
    icon: 356,
  },
  {
    code: 1246,
    day: "Mưa nặng",
    night: "Mưa nặng",
    icon: 359,
  },
  {
    code: 1249,
    day: "Mưa đá nhẹ",
    night: "Mưa đá nhẹ",
    icon: 362,
  },
  {
    code: 1252,
    day: "Mưa đá vừa hoặc nặng",
    night: "Mưa đá vừa hoặc nặng",
    icon: 365,
  },
  {
    code: 1255,
    day: "Tuyết nhẹ",
    night: "Tuyết nhẹ",
    icon: 368,
  },
  {
    code: 1258,
    day: "Tuyết vừa hoặc nặng",
    night: "Tuyết vừa hoặc nặng",
    icon: 371,
  },
  {
    code: 1261,
    day: "Mưa đá nhẹ",
    night: "Mưa đá nhẹ",
    icon: 374,
  },
  {
    code: 1264,
    day: "Mưa đá vừa hoặc nặng",
    night: "Mưa đá vừa hoặc nặng",
    icon: 377,
  },
  {
    code: 1273,
    day: "Mưa nhẹ có sấm",
    night: "Mưa nhẹ có sấm",
    icon: 386,
  },
  {
    code: 1276,
    day: "Mưa vừa hoặc nặng có sấm",
    night: "Mưa vừa hoặc nặng có sấm",
    icon: 389,
  },
  {
    code: 1279,
    day: "Tuyết nhẹ có sấm",
    night: "Tuyết nhẹ có sấm",
    icon: 392,
  },
  {
    code: 1282,
    day: "Tuyết vừa hoặc nặng có sấm",
    night: "Tuyết vừa hoặc nặng có sấm",
    icon: 395,
  },
];

export default conditonsData;
